"""`docs/supported.md` is generated by `tools/gen_supported.py`: the committed file must be what
the script writes, so the page cannot drift from the tables the integration uses."""

from __future__ import annotations

import importlib.util
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def _generator():
    spec = importlib.util.spec_from_file_location("gen_supported", ROOT / "tools" / "gen_supported.py")
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def test_supported_page_is_what_the_script_writes() -> None:
    generated = _generator().render()
    committed = (ROOT / "docs" / "supported.md").read_text(encoding="utf-8")
    assert committed == generated, "docs/supported.md is stale: run `python tools/gen_supported.py`"


def test_every_listed_integration_has_a_display_name() -> None:
    gen = _generator()
    domains = {platform for row in gen.sd.METER_ROWS for platform in row.platforms}
    domains |= {platform for row in gen.sd.BATTERY_ROWS for platform in row.platforms}
    domains |= {str(case["domain"]) for case in gen.vehicle_cases() if case["soc"] not in (None, "ambiguous")}
    missing = sorted(domain for domain in domains if domain not in gen.NAMES)
    assert not missing, f"add a display name to NAMES in tools/gen_supported.py: {missing}"


def test_page_has_one_section_per_category() -> None:
    text = _generator().render()
    for heading in (
        "# Supported EV chargers, meters, batteries and cars",
        "## Supported EV chargers",
        "## Supported grid meters",
        "## Supported house batteries",
        "## Supported vehicles",
        "## Supported solar forecast",
    ):
        assert f"\n{heading}\n" in f"\n{text}", heading
