// One source for the card's version: the integration's own manifest.
//
// The Lovelace resource URL is cache-busted by that version, so the version must not live in a
// second hand-kept place in TypeScript where a release can forget it. This script turns the
// manifest into a generated module; the build and the tests call it, and the generated file is
// not edited by hand.

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const manifestPath = resolve(here, "../../custom_components/spotnav/manifest.json");
const target = resolve(here, "../src/generated/version.ts");

const manifest = JSON.parse(readFileSync(manifestPath, "utf8"));
const version = manifest.version;
if (typeof version !== "string" || version.length === 0) {
  throw new Error(`No version in ${manifestPath}`);
}

const contents = `// Generated by frontend/scripts/write-version.mjs from
// custom_components/spotnav/manifest.json. Do not edit: run \`npm run version:write\`.
export const CARD_VERSION = ${JSON.stringify(version)};
`;

mkdirSync(dirname(target), { recursive: true });
try {
  if (readFileSync(target, "utf8") === contents) {
    process.exit(0);
  }
} catch {
  // Not written yet.
}
writeFileSync(target, contents);
console.log(`version ${version} -> src/generated/version.ts`);
